// Generated by gencpp from file astra_camera/GetUVCMirror.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_GETUVCMIRROR_H
#define ASTRA_CAMERA_MESSAGE_GETUVCMIRROR_H

#include <ros/service_traits.h>


#include <astra_camera/GetUVCMirrorRequest.h>
#include <astra_camera/GetUVCMirrorResponse.h>


namespace astra_camera
{

struct GetUVCMirror
{

typedef GetUVCMirrorRequest Request;
typedef GetUVCMirrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUVCMirror
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::GetUVCMirror > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::astra_camera::GetUVCMirror&) { return value(); }
};

template<>
struct DataType< ::astra_camera::GetUVCMirror > {
  static const char* value()
  {
    return "astra_camera/GetUVCMirror";
  }

  static const char* value(const ::astra_camera::GetUVCMirror&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::GetUVCMirrorRequest> should match
// service_traits::MD5Sum< ::astra_camera::GetUVCMirror >
template<>
struct MD5Sum< ::astra_camera::GetUVCMirrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::GetUVCMirrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetUVCMirrorRequest> should match
// service_traits::DataType< ::astra_camera::GetUVCMirror >
template<>
struct DataType< ::astra_camera::GetUVCMirrorRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::GetUVCMirrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::GetUVCMirrorResponse> should match
// service_traits::MD5Sum< ::astra_camera::GetUVCMirror >
template<>
struct MD5Sum< ::astra_camera::GetUVCMirrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::GetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::GetUVCMirrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::GetUVCMirrorResponse> should match
// service_traits::DataType< ::astra_camera::GetUVCMirror >
template<>
struct DataType< ::astra_camera::GetUVCMirrorResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::GetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::GetUVCMirrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_GETUVCMIRROR_H
