// Generated by gencpp from file astra_camera/SetUVCMirror.msg
// DO NOT EDIT!


#ifndef ASTRA_CAMERA_MESSAGE_SETUVCMIRROR_H
#define ASTRA_CAMERA_MESSAGE_SETUVCMIRROR_H

#include <ros/service_traits.h>


#include <astra_camera/SetUVCMirrorRequest.h>
#include <astra_camera/SetUVCMirrorResponse.h>


namespace astra_camera
{

struct SetUVCMirror
{

typedef SetUVCMirrorRequest Request;
typedef SetUVCMirrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUVCMirror
} // namespace astra_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::astra_camera::SetUVCMirror > {
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::astra_camera::SetUVCMirror&) { return value(); }
};

template<>
struct DataType< ::astra_camera::SetUVCMirror > {
  static const char* value()
  {
    return "astra_camera/SetUVCMirror";
  }

  static const char* value(const ::astra_camera::SetUVCMirror&) { return value(); }
};


// service_traits::MD5Sum< ::astra_camera::SetUVCMirrorRequest> should match
// service_traits::MD5Sum< ::astra_camera::SetUVCMirror >
template<>
struct MD5Sum< ::astra_camera::SetUVCMirrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::SetUVCMirrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetUVCMirrorRequest> should match
// service_traits::DataType< ::astra_camera::SetUVCMirror >
template<>
struct DataType< ::astra_camera::SetUVCMirrorRequest>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::SetUVCMirrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::astra_camera::SetUVCMirrorResponse> should match
// service_traits::MD5Sum< ::astra_camera::SetUVCMirror >
template<>
struct MD5Sum< ::astra_camera::SetUVCMirrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::astra_camera::SetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::SetUVCMirrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::astra_camera::SetUVCMirrorResponse> should match
// service_traits::DataType< ::astra_camera::SetUVCMirror >
template<>
struct DataType< ::astra_camera::SetUVCMirrorResponse>
{
  static const char* value()
  {
    return DataType< ::astra_camera::SetUVCMirror >::value();
  }
  static const char* value(const ::astra_camera::SetUVCMirrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASTRA_CAMERA_MESSAGE_SETUVCMIRROR_H
